### ISSUE TITLE
Proposal: Support Cluster API abstraction 

### ISSUE THREAD

**Issue by danehans** [contiv/cluster#91]
The Cluster Manager API currently implements node-level functionality, such as commissioning/decommissioning:

https://github.com/contiv/cluster/blob/master/management/src/clusterm/manager/api.go#L19-L23

This proposal suggests implementing top-level API objects required for providing cluster-level operations, such as:

**Kind**: A string value representing the REST resource this object represents. For example Node, Cluster, etc..
**Spec**: Specification of the desired behavior of the cluster/node.
**Cluster**: Cluster is one or more nodes that run in a cluster.
**ClusterSpec**: A description of a cluster.
**Node**: A standalone physical/virtual machine with predefined/discovered compute, memory, storage and networking capabilities.
**NodeSpec**: A description of a node.

Here is an example manifest that can be passed to Cluster Manager API to instantiate a Kubernetes cluster containing 10 nodes:
```
kind: Cluster
spec:
  type: kubernetes
  count: 10 # specifies the number of contiv/cluster nodes to commission.
...
```

Here is an example manifest that can be passed to the Cluster Manager API to instantiate a Swarm cluster containing 5 nodes:
```
kind: Cluster
spec:
  type: swarm
  count: 5 # specifies the number of contiv/cluster nodes to commission.
...
```

Additional **ClusterSpec** attributes can be introduced in the future, such as:
```
spec:
  os: coreos # the operating system used by nodes in the cluster
  target: baremetal # a target for instantiating a cluster ex> baremetal/vagrant/aws/openstack/etc
```
